### ISSUE TITLE
multiple client support for dtls server hosted in customized mqtt-sn gateway

### ISSUE THREAD

**Issue by imranbilal1** [eclipse/paho.mqtt-sn.embedded-c#150]
Hello,
i need to add threading support on mqttsn_gateway which shall do the following;
1. sensor should connect to the gateway through dtls tunnel for once in its entire active communication cycle
2(a). after successful dtls connection, gateway should allow the sensor to connect, publish and subscribe to the broker
2(b). moreover, if any-other sensor wants to communicate with the broker via same gateway then step 1 and 2(a) shall repeat

**so far what i have done is that i have developed a dtls session in gateway which actively listens for an incoming connection from a sensor and after secure handshake, it allows that sensor to do the rest of the work with that established dtls session.**

a few work around that i did but failed for adding multiple connection support are as follows;
-> i destroyed the established dtls session after processing a single packet (either connect, publish or sub) from the sensor and forced the gateway to initiate the tunnel again and listen for an incoming connection _**(this strategy demands to do dtls session establishment every time a sensor wants to connect - not affordable)**_ this model doesn't work with the paho_mqttsn_client library
-> i added thread support for the entire gateway application which 1st initiates the secure dtls session and then listens to the incoming dtls connection from sensor. Soon it gets a connection, it creates a child thread which simply do the handshake and on success, allows the gateway to run(). Moreover, the parent thread simply returns to the initiation of dtls session and waits for another incoming connection. **(this thread model acquires a lot of memory space which tends to crash or hang)** 

any help in this regard would worth appreciation.

Thanks,

**Comment by ty4tw** [comment]
Hi ImranBilalButt,

How about to use MQTT-SN forwarder ?
![image](https://user-images.githubusercontent.com/7830788/57266721-37902e00-70b8-11e9-867d-0cdb62c54402.png)
Forwarder and Gateway reside in the same host.

**Comment by ImranBilalButt** [comment]
hello @ty4tw 
do **paho.mqtt-sn.gateway** application have built-in support for 'MQTT-SN Forwarder'? if so, then how to configure that mode. Moreover, do MQTT-SN Forwarder allow built-in 
 support for multi-threading?

**Comment by ty4tw** [comment]
Hi,
Gateway is a gateway. It's not a forwarder.
you have to make your own forwarder.

**Comment by ImranBilalButt** [comment]
Hello @ty4tw 
thank you for your reply. 
we investigated your proposed solution of adding a forwarder to make it handle threaded dtls traffic from multiple clients but we concluded that, on functional level, forwarder would act almost like the mqtt-sn gateway which is not what we want bcz it would be time consuming, more complicated and comes with additional packet latency. 
nevertheless, we read some articles on different sites discussing about the need for adding dtls over udp traffic in mqtt-sn gateway **[https://devzone.nordicsemi.com/f/nordic-q-a/41054/mqttsn-with-dtls]**  where it is mentioned that the current mqtt-sn gateway version supports the AES-128 encryption for plain UDP traffic. We would like to consider it as a secondary/temporary solution but we are unable to find any details about it in mqtt-sn documentation. Kindly suggest any documentation or tutorial for enabling this AES-128 encryption in mqtt-sn if it is available.
Also, we are currently working on implementing **threaded dtls over udp server on mqtt-sn gateway** but it requires a lot of modifications in the actual program. Since, the program is not well documented, which makes it difficult to modify. Your collaboration in this matter would be helpful and will expedite the process.

Thanks,
