### ISSUE TITLE
Gateway doesn't send a PINGREQ after sending PUBLISH message

### ISSUE THREAD

**Issue by LucDigi** [eclipse/paho.mqtt-sn.embedded-c#165]
I'm trying out the examples from the nRF5 SDK for sleeping OpenThread nodes with MQTT-SN, the sleep behavior of a subscribed node is fine until there is a buffered message ready for it.
The node receives the message, but afterwards it doesn't go back to sleep and the gateway also never sends a tailing PINGRES(which it should according to MQTT-SN v1.2 spec if I'm not wrong). Does anyone have an idea what is going on here?

[MQTT-SN_log.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/3680527/MQTT-SN_log.txt)

**Comment by LucDigi** [comment]
I've modified the if else so that the PINGRES is always send and not skipped if there are queued messages, this seems to work fine for QOS-0 but I don't know if it will mess with higher QOS levels logic. Any feedback/suggestions on a proper fix would be great, but this is what I got right now:

/*
 *  PINGREQ
 */
void MQTTSNConnectionHandler::handlePingreq(Client* client, MQTTSNPacket* packet)
{
	if ( ( client->isSleep() || client->isAwake() ) &&  client->getClientSleepPacket() )
	{
	    sendStoredPublish(client);
		client->holdPingRequest();
	}
	//else
	//{
        /* send PINGREQ to the broker */
	    client->resetPingRequest();
        MQTTGWPacket* pingreq = new MQTTGWPacket();
        pingreq->setHeader(PINGREQ);
        Event* evt = new Event();
        evt->setBrokerSendEvent(client, pingreq);
        _gateway->getBrokerSendQue()->post(evt);
	//}
}

**Comment by ty4tw** [comment]
Hi LucDigi,

Thank you for your contribution.

**Comment by slavek1250** [comment]
I'd like to mention that the bug fix introduced in #165 is no longer available on master after #209 so this bug is still up to date. Based on MQTT-SN 1.2 specification broker/server should send a ping response after all cached messages for the client are sent.

"The transfer of messages to the client is closed by the server/gateway by means of a PINGRESP message, i.e. the server/gateway will consider the client as asleep and restart the sleep timer again after having sent the PINGRESP message."

https://www.oasis-open.org/committees/download.php/66091/MQTT-SN_spec_v1.2.pdf
