### ISSUE TITLE
Questions on MQTT-SN Gateway

### ISSUE THREAD

**Issue by icraggs** [eclipse/paho.mqtt-sn.embedded-c#17]
Thanks for the work Tomoaki.  I've just been trying out the gateway and I have some questions.

1) Why do we have to create the files rbmutex.key, ringbuffer.key and semaphore.key?  Is there a reason why the program can't do this itself?

2) I think the directory in which these files are located should be configurable.

3) You say "This must not be the same machine as the Client."   The gateway must not be on the same machine as the client?  Why is this the case?

4) Does the example param.conf file need any changes before it will work?  I'm getting "can't open the sensor network"

Thanks

**Comment by ty4tw** [comment]
Thank you for your question.   

1)  Why do we have to create the files....
 because of the access right.   regular user can't create files.

2)  the directory in which these files are located should be configurable.
 yes, that's a good idea. I've never think it. I will change ASAP.  then 1) will be solved.

3) Why is this the case?
GW can not receive Multicast packes from my clients (not paho clients) running in the same machine.
I did not dig into it.  because I thought there's no such chance in the field.

4) param.conf file need any changes ...
BroadcastIP and BroadcastPortNo should be MulticastIP and MulticastPortNo.
I will make a pull request to fix it.

Thank you again.

**Comment by ty4tw** [comment]
I made a pull request.
Now you can execute the gateway with out any setting.
Just make and execute.  that' all.  Default key files are created automatically.

I'm developing alone, so I need any opinion from others.  Thank you for your advise.

**Comment by icraggs** [comment]
3) is also affected by the multicast setting of receiving local packets.  I don't remember exactly, but the default is that the local host does not receive UDP multicast packets.  I'll find out again at some point.
