### ISSUE TITLE
Using the Gateway

### ISSUE THREAD

**Issue by icraggs** [eclipse/paho.mqtt-sn.embedded-c#23]
Tomoaki,

I've just been trying out the gateway.  Started up first time, which is great :-)

I've been using the client sample programs in MQTTSNPacket/samples

qos0pub_register: the first message gets sent, but then the gateway crashes:

20160809 215541 154   PUBLISH     0000  --->  d:quickstart:udptest:9002f7f1ad23 30 FF 01 00 19 69 6F 74 2D 32 2F 65 76 74 2F 73 74 61 74 75 73 2F 66 6D 74 2F 6A 73 6F 6E 00 00 7B 22 64 22 3A 7B 22 6D 79 4E 61 6D 65 22 3A 22 49 6F 54 20 6D 62 65 64 22 2C 22 61 63 63 65 6C 58 22 3A 31 32 2E 30 30 30 30 2C 22 61 63 63 65 6C 59 22 3A 31 30 2E 30 30 30 30 2C 22 61 63 63 65 6C 5A 22 3A 36 2E 30 30 30 30 2C 22 74 65 6D 70 22 3A 32 33 2E 30 30 30 30 2C 22 6A 6F 79 73 74 69 63
**\* stack smashing detected ***: ../Build/MQTT-SNGateway terminated
Aborted (core dumped)

qos0pub and qos01pub don't seem to work quite right - but I haven't figured out exactly what is going on yet.  I'll get more information if you don't first!

**Comment by ty4tw** [comment]
Ian,
Thank you for testing.
I guess the problem occurred in log print.  
payload length of my test case is 70.  so, never happened.
I will check it.  

        int BrokerRecvTask::log(Client* client, MQTTGWPacket* packet)
        {
	       char pbuf[SIZEOF_LOG_PACKET * 3];
	       char msgId[6];
	       int rc = 0;

   buffer size is smaller than required size.
             char pbuf[ (SIZEOF_LOG_PACKET **+ 5**) * 3];    

**5** means  Fix header length  **2** + remaining field length  **3**.
 

    int BrokerRecvTask::log(Client* client, MQTTGWPacket* packet)
    {
	    char pbuf[SIZEOF_LOG_PACKET * 3];
	    char msgId[6];
	    int rc = 0;

	    switch (packet->getType())
	   {
                          ..........        
	    case PUBLISH:
		    WRITELOG(FORMAT_GR_MSGID_NL, currentDateTime(), packet->getName(), packet->getMsgId(msgId), LEFTARROW, client->getClientId(), packet->print(pbuf));
		    break;
	    case PUBACK:
	    case PUBREC:
	    case PUBREL:
	    case PUBCOMP:
		    WRITELOG(FORMAT_GR_MSGID, currentDateTime(), packet->getName(), packet->getMsgId(msgId), LEFTARROW, client->getClientId(), packet->print(pbuf));
	               ................    
		    break;
	    default:
		    rc = -1;
		    break;
	    }
	    return rc;
    }

    char* MQTTGWPacket::print(char* pbuf)
    {
	    char* ptr = pbuf;
	    char** pptr = &pbuf;
	    char digit[4];

	    sprintf(*pptr, " %02X",(const unsigned char)_header.byte);
	    *pptr += 3;
	    int len = MQTTPacket_encode((char*) digit, _remainingLength);
	    for (int i = 0; i < len; i++)
	    {
		    sprintf(*pptr, " %02X", digit[i]);
		    *pptr += 3;
	    }

	    int size = _remainingLength > SIZEOF_LOG_PACKET ? SIZEOF_LOG_PACKET : _remainingLength;
	    for (int i = 0; i < size; i++)
	    {
		    sprintf(*pptr, " %02X", *(_data + i));
		    *pptr += 3;
	    }
	    **pptr = 0;
	    return ptr;
    }
   

I have one question.  ClientId length was more than 23.   (d:quickstart:udptest:9002f7f1ad23)    
MQTTSNPacket::getCONNECT(MQTTSNPacket_connectData* data)  should check the length of ID.

**Comment by ty4tw** [comment]
I fixed the bug.   

**Reproduction test**

20160810 131838 123   SEARCHGW          <---  Client                     01 00
20160810 131838 123   GWINFO            --->  Clients                    02 01
20160810 131838 395   CONNECT           <---  ESP8266-08b133             04 04 01 03 84 45 53 50 38 32 36 36 2D 30 38 62 31 33 33
20160810 131839 415   CONNECT           --->  ESP8266-08b133             10 1A 00 04 4D 51 54 54 04 02 03 84 00 0E 45 53 50 38 32 36 36 2D 30 38 62 31 33 33
20160810 131839 704   CONNACK           <---  ESP8266-08b133             20 02 00 00
20160810 131839 705   CONNACK           --->  ESP8266-08b133             05 00

20160810 131839 712   REGISTER    0002  <---  ESP8266-08b133             0A 00 00 00 02 74 79 34 74 77 40 67 69 74 68 75 62 2F 6F 6E 6F 66 66 2F 61 72 64 75 69 6E 6F
20160810 131839 712   REGACK      0002  --->  ESP8266-08b133             0B 00 01 00 02 00

20160810 131839 860   PUBLISH     0001  <---  ESP8266-08b133             0C 20 00 01 00 01 05 00 00 00 00 00 00 00 01 00 00 00 02 00 00 00 46 F0 21 40 30 FA FE 3F 66 86 FE 3F 6F FA FE 3F 02 00 00 00 00 00 00 00 10 00 00 00 48 D8 FF 3F 00 00 00 00 10 57 76 00 2A 29 10 40 00 01 00 00 0C 00 00 00 08 9A FE 3F 08 9A FE 3F 80 FA FE 3F B0 FA FE 3F 38 6F 10 40 95 0C FF 3F 08 00 00 00 48 EB FE 3F 01 00 00 00 31 FA FE 3F 08 95 20 40 78 C2 FF 3F C4 26 10

20160810 131839 860   PUBLISH     0001  --->  ESP8266-08b133             32 FF 04 00 1A 74 79 34 74 77 40 67 69 74 68 75 62 2F 6F 6E 6F 66 66 2F 61 72 64 75 69 6E 6F 00 01 05 00 00 00 00 00 00 00 01 00 00 00 02 00 00 00 46 F0 21 40 30 FA FE 3F 66 86 FE 3F 6F FA FE 3F 02 00 00 00 00 00 00 00 10 00 00 00 48 D8 FF 3F 00 00 00 00 10 57 76 00 2A 29 10 40 00 01 00 00 0C 00 00 00 08 9A FE 3F 08 9A FE 3F 80 FA FE 3F B0 FA FE 3F 38 6F 10 40 95 0C FF 3F 08 00 00 00 48 EB
*** stack smashing detected ***: ./MQTTSN-embedded-C terminated

**To Fix the Bug  change code  "char pbuf[ (SIZEOF_LOG_PACKET + 5) * 3];** 
 **Result is:**

20160810 132201 815   SEARCHGW          <---  Client                     01 00
20160810 132201 815   GWINFO            --->  Clients                    02 01
20160810 132201 821   CONNECT           <---  ESP8266-08b133             04 04 01 03 84 45 53 50 38 32 36 36 2D 30 38 62 31 33 33
20160810 132202 111   CONNECT           --->  ESP8266-08b133             10 1A 00 04 4D 51 54 54 04 02 03 84 00 0E 45 53 50 38 32 36 36 2D 30 38 62 31 33 33
20160810 132203 703   CONNACK           <---  ESP8266-08b133             20 02 00 00
20160810 132203 703   CONNACK           --->  ESP8266-08b133             05 00

20160810 132203 714   REGISTER    0002  <---  ESP8266-08b133             0A 00 00 00 02 74 79 34 74 77 40 67 69 74 68 75 62 2F 6F 6E 6F 66 66 2F 61 72 64 75 69 6E 6F
20160810 132203 714   REGACK      0002  --->  ESP8266-08b133             0B 00 01 00 02 00

20160810 132203 869   PUBLISH     0001  <---  ESP8266-08b133             0C 20 00 01 00 01 05 00 00 00 00 00 00 00 01 00 00 00 02 00 00 00 46 F0 21 40 30 FA FE 3F 66 86 FE 3F 6F FA FE 3F 02 00 00 00 00 00 00 00 10 00 00 00 48 D8 FF 3F 0C 05 00 40 F9 3D 38 00 2A 29 10 40 00 01 00 00 0C 00 00 00 30 00 00 00 1F 00 00 00 80 FA FE 3F B0 FA FE 3F 38 6F 10 40 95 0C FF 3F 08 00 00 00 48 EB FE 3F 01 00 00 00 31 FA FE 3F 08 95 20 40 FF FF FF FF FC C6 FF

20160810 132203 869   PUBLISH     0001  --->  ESP8266-08b133             32 FF 04 00 1A 74 79 34 74 77 40 67 69 74 68 75 62 2F 6F 6E 6F 66 66 2F 61 72 64 75 69 6E 6F 00 01 05 00 00 00 00 00 00 00 01 00 00 00 02 00 00 00 46 F0 21 40 30 FA FE 3F 66 86 FE 3F 6F FA FE 3F 02 00 00 00 00 00 00 00 10 00 00 00 48 D8 FF 3F 0C 05 00 40 F9 3D 38 00 2A 29 10 40 00 01 00 00 0C 00 00 00 30 00 00 00 1F 00 00 00 80 FA FE 3F B0 FA FE 3F 38 6F 10 40 95 0C FF 3F 08 00 00 00 48 EB
20160810 132204 149   PUBACK      0001  <---  ESP8266-08b133             40 02 00 01
20160810 132204 149   PUBACK      0001  --->  ESP8266-08b133             0D 00 01 00 01 00

**Comment by ty4tw** [comment]
Ian,

I created a pull request to fix this bug.
BTW, I'm using ESP8266 client.  It's quite cheap less than 10 USDs.
![esp8266client](https://cloud.githubusercontent.com/assets/7830788/17542451/c9fd3e64-5f03-11e6-90ca-b50416c1582c.JPG)

**Comment by icraggs** [comment]
Thanks Tomoaki.  The 23 character limit on client id was removed in MQTT 3.1.1.   When these basic tests work I will ask for more people to try out the gateway so we get more testing.

**Comment by ty4tw** [comment]
Ian,
we needs a lot of tests to find the bugs.
and  I have a enough time to fix them.  I'm free old man.
I check the MQTT 3.1.1. and found max length is 64K.  I didn't know that.
ClientId length is defined in MQTT-SN 1.2 also. and it is still less than 23 digit.
This will change in future.  so,  I have to change the ClientId related codes of the Gateway first.  
64K is not a realistic length.   it should be specified with MAX_CLIENTID_LENGTH.

**Comment by icraggs** [comment]
I never held with the 23 character clientid length particularly, so we should not hold to it in MQTT-SN either.  I will try to get the specification updated.  The maximum length in MQTT-SN depends on the maximum packet length, which can vary depending on a particular implementation.  In practice, we need more than 23 characters, but probably less than 100.

I just tried your fix, which works fine.  There is something strange though with the contents of the packets.  Using qos0pub_register in the MQTTSNPacket samples, and an MQTT subscriber (paho_c_sub of the Paho MQTT C client), messages did not print out as expected after connecting the gateway to RSMB and then subscribing to the MQTT topic.  

I swapped out the gateway for RSMB with MQTT-SN and the contents were printed correctly.  Could you try this scenario out and find out what the problem is?  RSMB is in the Mosquitto repository on Github.  

If you make sure the other sample MQTTSNPacket samples work correctly as well, this would be a great next step.  I am able to help debug these tests, but maybe not for a couple of weeks.

Some other comments:

- the default MQTT server to use should be iot.eclipse.org rather than test.moquitto.org
- the gateway should print out some information when it starts up: Eclipse Paho, copyright statements, (and your name and email address if you wish)
- the copyright statements in the source files aren't right.  See https://eclipse.org/legal/copyrightandlicensenotice.php.  The final date of the range should be the latest year in which the source file was updated (probably 2016), and your name should be on the copyright statement as well as IBM's
- how would you feel about writing some automated tests for the gateway?

Sorry to hear that you don't have a job - maybe this work in Paho will serve to highlight your work.   I appreciate the contributions you are making, I think this gateway could be a significant part of Paho.

**Comment by ty4tw** [comment]
Ian,
> Could you try this scenario out and find out what the problem is?
sure, I will try.

> how would you feel about writing some automated tests for the gateway?
YES we need it.

**Comment by ty4tw** [comment]
Ian, 
I understand what you mean that messages did not print out as expected .

this cause might be a remaining length of PUBLISH.
current remaining  length value is 0xFF 0x01. this should be 0x01 0xFF.
I will test this tomorrow.   ( I can not connect to the broker now.)

     int MQTTGWPacket::getPacketData(unsigned char* buf)
    {
	    unsigned char* ptr = buf;
	    unsigned char  rlen[4];      // add

	    *ptr++ = _header.byte;
	    int len = MQTTPacket_encode((char*)rlen, _remainingLength);
	    for ( int i = len; i < 0; i-- )     // add
	    {                                         // add
		    *ptr++ = rlen[i - 1];     // add
	    }                                        // add
            // ptr += len;   
	    memcpy(ptr, _data, _remainingLength);
	    return 1 + len + _remainingLength;
    }

**Comment by ty4tw** [comment]
I could not find the reason of the problem.

Result of my test;

 1) I changed TopicName to ty4tw/iot-2/evt/status/fmt/json in order to unused Topic.
 2) I used qos0pub_register to send messages and I change TopicName and QoS setting also.
 1) in case of PUBLISH with Qos0, paho_c_sub could not recieve any thing.
 2) in case of PUBLISH with QoS1, paho_c_sub could recive the message as follows.
	  
qos0pub_register sends MQTT-SN PUBLISH packet:
20160813 102805.525   PUBLISH     0005  <---  d:quickstart:udptest:9002f7f1ad2    0C 20 00 01 00 05 7B 22 64 22 3A 7B 22 6D 79 4E 61 6D 65 22 3A 22 49 6F 54 20 6D 62 65 64 22 2C 22 61 63 63 65 6C 58 22 3A 31 38 2E 30 30 30 30 2C 22 61 63 63 65 6C 59 22 3A 31 36 2E 30 30 30 30 2C 22 61 63 63 65 6C 5A 22 3A 34 2E 30 30 30 30 2C 22 74 65 6D 70 22 3A 32 30 2E 30 30 30 30 2C 22 6A 6F 79 73 74 69 63 6B 22 3A 22 53 4E 2D 44 4F 57 4E 22 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 31 22 3A 31 35 30 2E 30 30 30 30 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 32 22 3A 32 31 30 2E 30 30 30 30 7D 7D

Gateway sends MQTT PUBLISH packet:
20160813 102805.525   PUBLISH     0005  --->  d:quickstart:udptest:9002f7f1ad2    32 FF 01 00 1F 74 79 34 74 77 2F 69 6F 74 2D 32 2F 65 76 74 2F 73 74 61 74 75 73 2F 66 6D 74 2F 6A 73 6F 6E 00 05 7B 22 64 22 3A 7B 22 6D 79 4E 61 6D 65 22 3A 22 49 6F 54 20 6D 62 65 64 22 2C 22 61 63 63 65 6C 58 22 3A 31 38 2E 30 30 30 30 2C 22 61 63 63 65 6C 59 22 3A 31 36 2E 30 30 30 30 2C 22 61 63 63 65 6C 5A 22 3A 34 2E 30 30 30 30 2C 22 74 65 6D 70 22 3A 32 30 2E 30 30 30 30 2C 22 6A 6F 79 73 74 69 63 6B 22 3A 22 53 4E 2D 44 4F 57 4E 22 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 31 22 3A 31 35 30 2E 30 30 30 30 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 32 22 3A 32 31 30 2E 30 30 30 30 7D 7D

Broker sends MQTT PUBACK:
20160813 102805.734   PUBACK      0005  <---  d:quickstart:udptest:9002f7f1ad2    40 02 00 05

Gateway send MQTT-SN PUBACK to qos0pub_register.
20160813 102805.734   PUBACK      0005  --->  d:quickstart:udptest:9002f7f1ad2    0D 00 01 00 05 00

paho_c_sub could get packets as follows
$ ./paho_c_sub ty4tw/iot-2/evt/status/fmt/json --host iot.eclipse.org --port 1883 --qos 0

{"d":{"myName":"IoT mbed","accelX":12.0000,"accelY":10.0000,"accelZ":6.0000,"temp":23.0000,"joystick":"SN-CENTRE","potentiometer1":180.0000,"potentiometer2":90.0000}}{"d":{"myName":"IoT mbed","accelX":18.0000,"accelY":0.0000,"accelZ":14.0000,"temp":20.0000,"joystick":"SN-RIGHT","potentiometer1":270.0000,"potentiometer2":60.0000}}{"d":{"myName":"IoT mbed","accelX":2.0000,"accelY":12.0000,"accelZ":4.0000,"temp":24.0000,"joystick":"SN-LEFT","potentiometer1":180.0000,"potentiometer2":90.0000}}{"d":{"myName":"IoT mbed","accelX":6.0000,"accelY":4.0000,"accelZ":0.0000,"temp":20.0000,"joystick":"SN-DOWN","potentiometer1":210.0000,"potentiometer2":240.0000}}{"d":{"myName":"IoT mbed","accelX":18.0000,"accelY":16.0000,"accelZ":4.0000,"temp":20.0000,"joystick":"SN-DOWN","potentiometer1":150.0000,"potentiometer2":210.0000}}{"d":{"myName":"IoT mbed","accelX":6.0000,"accelY":18.0000,"accelZ":4.0000,"temp":19.0000,"joystick":"SN-RIGHT","potentiometer1":90.0000,"potentiometer2":210.0000}}{"d":{"myName":"IoT mbed","accelX":10.0000,"accelY":8.0000,"accelZ":16.0000,"temp":25.0000,"joystick":"SN-DOWN","potentiometer1":270.0000,"potentiometer2":30.0000}}


3. What is the difference of the packet data between QoS0 and QoS1 of my test.
 
in case of QoS0   result NG  
20160813 103459.586   PUBLISH     0000  --->  d:quickstart:udptest:9002f7f1ad2   30 FF 01 　　　00 1F 74 79 34 74 77 2F 69 6F 74 2D 32 2F 65 76 74 2F 73 74 61 74 75 73 2F 66 6D 74 2F 6A 73 6F 6E    00 00    7B 22 64 22 3A 7B 22 6D 79 4E 61 6D 65 22 3A 22 49 6F 54 20 6D 62 65 64 22 2C 22 61 63 63 65 6C 58 22 3A 32 2E 30 30 30 30 2C 22 61 63 63 65 6C 59 22 3A 31 32 2E 30 30 30 30 2C 22 61 63 63 65 6C 5A 22 3A 34 2E 30 30 30 30 2C 22 74 65 6D 70 22 3A 32 34 2E 30 30 30 30 2C 22 6A 6F 79 73 74 69 63 6B 22 3A 22 53 4E 2D 4C 45 46 54 22 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 31 22 3A 31 38 30 2E 30 30 30 30 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 32 22 3A 39 30 2E 30 30 30 30 7D 7D

in case of QoS1   result OK
20160813 102805.525   PUBLISH     0005  --->  d:quickstart:udptest:9002f7f1ad2   32 FF 01 　　　00 1F 74 79 34 74 77 2F 69 6F 74 2D 32 2F 65 76 74 2F 73 74 61 74 75 73 2F 66 6D 74 2F 6A 73 6F 6E    00 05    7B 22 64 22 3A 7B 22 6D 79 4E 61 6D 65 22 3A 22 49 6F 54 20 6D 62 65 64 22 2C 22 61 63 63 65 6C 58 22 3A 31 38 2E 30 30 30 30 2C 22 61 63 63 65 6C 59 22 3A 31 36 2E 30 30 30 30 2C 22 61 63 63 65 6C 5A 22 3A 34 2E 30 30 30 30 2C 22 74 65 6D 70 22 3A 32 30 2E 30 30 30 30 2C 22 6A 6F 79 73 74 69 63 6B 22 3A 22 53 4E 2D 44 4F 57 4E 22 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 31 22 3A 31 35 30 2E 30 30 30 30 2C 22 70 6F 74 65 6E 74 69 6F 6D 65 74 65 72 32 22 3A 32 31 30 2E 30 30 30 30 7D 7D

# Spaces before Topic, PacketId and Payload are putted for clarity.
#  01___00 1F... ,  6F 6E____00 00____7B 22 64 ... and  6F 6E____00 05____7B 22 64 ...

1) Payload is different. (normal)
 2) PacketId is differnt.   QoS0 is 0000 and QoS1 is 0001 to 0007  (normal)
 3) Header field is differnt.  QoS0 is 0x30.  QoS1 is 0x32. (normal)

Ian, 
Could you try QoS1 to reproduce ?

**Comment by ty4tw** [comment]
I found that QoS0 messages which were sent by the gaetway were returned from the broker.  but paho_c_sub output any thing. 
see wireshark screen shot of the packet from the broker.  
how strange.  What's the difference between RSMB and iot.eclipse.org.
Ian, could you check the difference? I don't know how to use RSMB. 

![wireshark](https://cloud.githubusercontent.com/assets/7830788/17646833/ef6c788a-6215-11e6-99f3-dc4e4cbcafe5.png)

**Comment by ty4tw** [comment]
Gateway has no problem.  
see this [video.](https://youtu.be/h1x7uWmLsDM)

**Comment by ty4tw** [comment]
Ian,

I made a gateway test program named GatewayTester.
and I added it to MQTTSNGateway/GatewayTester/sample/mainTest.cpp and mainTemplate.cpp
```    
$ cd  ....../MQTTSNGateway/GatewayTester 
$ make
$ make install
$ cd ../../../
$ ./MQTT-SNGatewayTester
```    
This program can run in a same PC the gateway is running.

see    .../MQTTSNGateway/GatewayTester/README

**Comment by icraggs** [comment]
Thanks for the updates Tomoaki.  I will look into it and try it out this weekend.

**Comment by icraggs** [comment]
The pull request has some conflicts, so I will have to resolve them before merging.  And I like the video :+1:

**Comment by ty4tw** [comment]
I think you can close this Issue.

**Comment by ty4tw** [comment]
Hi Ian,
Please close this issue.

**Comment by icraggs** [comment]
Oh, yes, I can close the issue.   Thanks!
